name : Communicating with Cliq

on:
  branch_protection_rule:
    #types : [created , edited , deleted]
  check_run:
    #types : [created , rerequested , completed , requested_action]
  check_suite:
    #types : [completed]
  create:
    # No Types
  delete:
    # No Types
  deployment:
    # No Types
  deployment_status:
    # No Types
  discussion:
    # types : [created , edited , deleted , transferred , pinned , unpinned , labeled , unlabeled , locked , unlocked , category_changed , answered , unanswered]
  discussion_comment:
    # types : [created , edited , deleted]
  fork:
    # No Types
  gollum:
    # No Types
  issues:
    # types : [opened , edited , deleted , transferred , pinned , unpinned , closed , reopened , assigned , unassigned , labeled , unlabeled , locked , unlocked , milestoned , demilestoned]
  issue_comment:
    # Use this for pull_Request_comment also
    # types : [created , edited , deleted]
  label:
    # types : [created , edited , deleted]
  merge_group:
    # types : [checks_requested]
  milestone:
    # types : [created , closed , opened , edited , deleted]
  page_build:
    # No types
  project:
    # types : [created , closed , reopened , edited , deleted]
  project_card:
    # types : [created , moved , converted , edited , deleted]
  project_column:
    # types : [created , updated , moved , deleted]
  public:
    # No Types
  pull_request:
    # It works only for opened , synchronize and reopened if not specified
    types: [ assigned , unassigned , labeled , unlabeled , opened , closed , edited , reopened , synchronize , converted_to_draft , ready_for_review , locked , unlocked , review_requested , review_request_removed , auto_merge_enabled , auto_merge_disabled ]
  pull_request_target:
    # It works only for opened , synchronize and reopened if not specified
    types: [ assigned , unassigned , labeled , unlabeled , opened , closed , edited , reopened , synchronize , converted_to_draft , ready_for_review , locked , unlocked , review_requested , review_request_removed , auto_merge_enabled , auto_merge_disabled ]
  pull_request_review:
    # types : [submitted , edited , dismissed]
  pull_request_review_comment:
    # types : [created , edited , deleted]
  push:
    # No Types
  registry_package:
    # types : [published , updated]
  release:
    # types : [published , unpublished , created , edited , deleted , prereleased , released]
  repository_dispatch:
    # User Defined Types
    types: [on-demand-test]
  schedule:
    # 'Minute Hour Date Month Day'
    # 'Starting_Minute/Step_Value Hour Date Month , Day'
    - cron: '1/5 * * * *'
  status:
    # No Types
  watch:
    # types : [started]
  workflow_dispatch:
    # No Types
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment: CliqInformer
    steps:
      - name: Set Up Checkout
        uses: actions/checkout@v1
      - name: Set Up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'temurin'
      - name: Set Up CliqInformer
        uses: prembala1710/CliqInformer@v0.0.11
        with:
          channel-endpoint: ${{ secrets.ENDPOINT }}
          watch-message: ':fireworks: (me) has starred your Repository (repo)'
          # false makes CliqInformer not send the default messsage if custom message is not set
