name : Communicating with Cliq

on:
  branch_protection_rule:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
  discussion_comment:
  fork:
  gollum:
  issues:
  issue_comment:
  label:
  merge_group:
  milestone:
  page_build:
  public:
  pull_request:
    types: [opened,closed,reopened,created,edited]
  pull_request_target:
  pull_request_review:
  pull_request_review_comment:
  push:
  registry_package:
  release:
  repository_dispatch:
    types: [on-demand-test]
  schedule:
    - cron: '0 12 * * *'
  status:
  watch:
  workflow_dispatch:
  
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/CliqInformer
        with:
          channel-endpoint: ${{ secrets.ENDPOINT }}
  test_name:
    runs-on: ubuntu-latest
    steps:
      - uses: CliqGeeks/CliqInformer@v1
        with:
          channel-endpoint: ${{ secrets.ENDPOINT }}
