name : Communicating with Cliq

on:
  [push,pull_request,watch]
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: prembala1710/CliqInformer@v0.0.11.1
        with:
          channel-endpoint: ${{ secrets.ENDPOINT }}
          branch-protection-rule-message: 'Security Update ​:Security:\n (event) is (action) by (me) at (repo) under (ref)'
          check-run-message: 'Check Run Status :server:\n (event) is (action) by (me) at (repo) under (ref)'
          check-suite-message: 'Check Suite Status :server:\n (event) is (action) by (me) at (repo) under (ref)'
          create-message: 'Creation :task:\n A (event) has occured'
          delete-message: 'Delete :milestone:\n A (event) has occured'
          deployment-message: 'Deployment :server:\n (event) is made successfully'
          deployment-status-message: 'Deployment Status Updated :server:\n (event) is completed successfully'
          discussion-message: 'Discussions :idea:\n A (event) has been (action)'
          discussion-comment-message: 'Discussion Comment :idea:\n A (event) has been (action)'
          fork-message: '(repo) has been forked by (me) under (ref)'
          gollum-message: 'A (event) has Occured'
          issues-message: 'Oops :surprise:\n A (event) is (action) by (me) at (repo) under (ref)'
          issue-comment-message: 'Hey :awe:\n (workflow) (event) has been (action) by (me) at (repo) under (ref)'
          label-message: 'Seems Like New Issues required New Labels :curious:\n A (event) has been (action) by (me)'
          merge-group-message: '(workflow) is triggered by (me) at (repo) under (ref)'
          milestone-message: 'Goals need to be Changed as the Project Progresses :milestone:\n A (event) is (action)'
          page-build-message: '(ref) Branch of (event) is changed by (me)'
          project-message: 'Good Projects are planned well:report:\n A (event) is (action) by (me) at (ref)'
          project-card-message: 'Good Projects are planned well:report:\n A (event) is (action) by (me) at (ref)'
          project-column-message: 'Good Projects are planned well:report:\n A (event) is (created) by (me) at (ref)'
          public-message: 'An Idea is Beneficial Only when it gives back to the Community :peace:\n (repo) is now Public :celebrate:'
          pull-request-message: 'A (event) is (action) at (repo) under (ref)'
          pull-request-comment-message: 'You have got a Comment for a Pull Request Dude :curious:\n A (event) is (action) at (repo) under (ref)'
          pull-request-target-message: 'A (event) is (action) at (repo) under (ref)'
          pull-request-review-message: 'You have got a Review Dude :curious:\n A (event) is (action) at (repo) under (ref)'
          pull-request-review-comment-message: 'You have got a Review Comment Dude :curious:\n A (event) is (action) at (repo) under (ref)'
          push-message: 'A (event) is made into (repo) under (ref).\n Good to see you make some Changes :new-year:'
          registry-package-message: ':gift-box: A Build is (action) at (repo)'
          release-message: ':target: (ref) has been (action) Successfully'
          repository-dispatch-message: ':report: A (event) has triggered this following workflow: (workflow)'
          schedule-message: 'Scheduled Event Trigger :calendar:\n (workflow) has been Scheduled to run at this time. Take a Look at it here (workflow)'
          status-message: 'Status has been Updated at (repo)'
          watch-message: ':fireworks: (me) has starred your Repository (repo)'
          workflow-dispatch-message: ':office: (workflow) has been dispatched by (me) at (repo) under (ref)'
          default-message: '(event) has happened. Hope You are Aware of it :wink:'
          # the message sent when the user doesn't want to enter all the 35 messages and just handle the same message to different messages.
          # this message is sent only when the custom message is not provided by the user.
          # ie. if a push occurs the push-message will be sent. In case it is not provided. The default-message will be sent. 
          # If the default-message is not given by user, 'The Workflow (workflow) is triggered by a (event) (action) by (me) at Repository (repo) under (ref)' will be sent 
          set-message-if-none: true
          # false makes CliqInformer not send the system defined default message if custom message is not set
          # isn't checked if default-message is given
